# COLOURS
from datetime import date

HEX_COLOUR_BASE = 16
HEX_COLOUR_LENGTH = 6
HEX_PRIMARY_COLOUR_LENGTH = 2
HEX_COLOUR_RED_SLICE = slice(0, 2)
HEX_COLOUR_GREEN_SLICE = slice(2, 4)
HEX_COLOUR_BLUE_SLICE = slice(4, 6)

# COORDINATES
MIN_LATITUDE = -90
MAX_LATITUDE = 90
MIN_LONGITUDE = -180
MAX_LONGITUDE = 180

# DATE RANGES
UNBOUNDED_START_DATE = date.fromisoformat("1000-01-01")
UNBOUNDED_END_DATE = date.fromisoformat("3000-01-01")

# BLOCK IDs
WPG_BLOCK_ID_TOKEN_DELIMITER = "-"
WPG_BLOCK_ID_NUM_TOKENS = 3
WPG_BLOCK_ID_SERVICE_ID_TOKEN_INDEX = 0
WPG_BLOCK_ID_ROUTE_FAMILY_TOKEN_INDEX = 1
WPG_BLOCK_ID_NUMBER_TOKEN_INDEX = 2