# COLOURS
HEX_COLOUR_BASE = 16
HEX_COLOUR_LENGTH = 6
HEX_PRIMARY_COLOUR_LENGTH = 2
HEX_COLOUR_RED_SLICE = slice(0, 2)
HEX_COLOUR_GREEN_SLICE = slice(2, 4)
HEX_COLOUR_BLUE_SLICE = slice(4, 6)

# COORDINATES
MIN_LATITUDE = -90
MAX_LATITUDE = 90
MIN_LONGITUDE = -180
MAX_LONGITUDE = 180